title: About Me
author: Rachel Ai
email: raiccoon936@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  

# social links
instagram_username: raiccoon
github_username:  raiccoon

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
